[conditions]
ratiometric_dye = 1
group1 = "kontrol"
group2 = "X3"

[treatments]
    [baseline]
    begin = 0
    end = 60
    [AITC]
    begin = 60
    end = 300
    [K+]
    begin = 300
    end = 360