[conditions]
ratiometric_dye = "Yes"
group1 = "kontrol"
group2 = "X3"

[treatments]
    [treatments.baseline]
    begin = 0
    end = 60
    [treatments.AITC]
    begin = 60
    end = 300
    [treatments.KCl]
    begin = 300
    end = 360