[project]
name = "neuron"
version = "1.0.1"
description = "Helps analyze data for my Ca measurement microscopy workflows. Determines what agonists cells reacted to and how strongly."
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "marimo>=0.23.8",
    "matplotlib>=3.10.3",
    "numpy>=2.0",
    "openpyxl>=3.1.5",
    "pandas>=2.3.0",
    "python-calamine>=0.4.0",
    "pyyaml>=6.0.3",
    "scipy>=1.17.1",
    "toml>=0.10.2",
]

[dependency-groups]
dev = [
    "pylsp-rope>=0.1.17",
    "pytest>=8.4.1",
    "python-lsp-ruff>=2.3.1",
    "python-lsp-server>=1.14.0",
    "snakeviz>=2.2.2",
    "websockets>=16.0",
]
